# nixpacks.toml

# Specify providers, Python is usually auto-detected but being explicit is good.
providers = ["python"]

# Define phases for the build
[phases.setup]
# List Nix packages needed.
# The exact names might vary slightly; you can search for them on search.nixos.org/packages
nixPkgs = [
    "pkgs.python312",  # Or let Nixpacks determine Python from your project
    "pkgs.rar",
    "pkgs.unrar",
    "pkgs.wget",
    "pkgs.curl"
]

# Nixpacks will typically detect and install from requirements.txt automatically
# if 'providers = ["python"]' is set and requirements.txt exists.
# If you needed to run custom pip install commands, you could add an [phases.install] section.
# [phases.install]
# cmds = [
#   "pip install --upgrade pip",
#   "pip install --no-cache-dir -r requirements.txt"
# ]


# Define the start command for your application
[start]
cmd = "gunicorn main:app -b 0.0.0.0:8000"
