[phases.setup]
# List Nix packages needed.
# pkgs.rar provides both 'rar' and 'unrar' commands.
nixPkgs = [
    "pkgs.python312",  # Or let Nixpacks determine Python from your project
    "pkgs.rar",        # This is all you need for rar and unrar
    "pkgs.wget",
    "pkgs.curl"
]
