[phases.setup]
nixPkgs = [
    "pkgs.python312",  # Or let Nixpacks determine Python from your project
    "pkgs.rar",        # THIS PROVIDES BOTH 'rar' AND 'unrar'
    "pkgs.p7zip",      # THIS PROVIDES '7z' FOR 7-ZIP SUPPORT
    "pkgs.wget",       # Download files from web servers
    "pkgs.curl"        #  Transfer data --to/from-- servers
]

[start]
cmd = "gunicorn main:app"
